services:

  postgres:
    image: postgres:15-alpine
    container_name: socialmedia-postgres
    environment:
      POSTGRES_DB: SocialMediaAppDB
      POSTGRES_USER: SocialMediaApp
      POSTGRES_PASSWORD: Abdoumimi12
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: socialmedia-redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: socialmedia-mongo
    ports:
      - "27017:27017"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: socialmedia-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: springApp
      KEYCLOAK_ADMIN_PASSWORD: Abdoumimi12
    ports:
      - "8180:8080"